TOOLS_LOG_PATH = 'C:/Users/ilin-mi/Desktop/Копия ToolsLog.xlsx'
SVOD_EXCEL_PATH = 'C:/Users/ilin-mi/Desktop/Копия SvodExcel.xlsx'
OUTPUT_PATH = 'C:/Users/ilin-mi/Desktop/'
OUTPUT_FILE_NAME = 'Тест обработки'
OUTPUT_FILE_TYPE = '.xlsx'